/**
 * @file nielsen-heuristics.ts
 * @description Nielsen's 10 Usability Heuristics with examples, violations, and evaluation questions
 * @author Charley Scholz, ELEV8
 * @coauthor Claude 4.6 Opus, Claude Code (coding assistant), Cursor (IDE)
 * @created 2026-02-23
 * @updated 2026-02-23
 */

export interface NielsenHeuristic {
  readonly id: number;
  readonly name: string;
  readonly description: string;
  readonly goodExamples: readonly string[];
  readonly violationExamples: readonly string[];
  readonly evaluationQuestions: readonly string[];
}

export const NIELSEN_HEURISTICS: readonly NielsenHeuristic[] = [
  {
    id: 1,
    name: 'Visibility of System Status',
    description: 'The design should always keep users informed about what is going on, through appropriate feedback within a reasonable amount of time. When users know the current system status, they learn the outcome of their prior interactions and determine next steps.',
    goodExamples: [
      'Progress bar during file upload showing percentage and estimated time',
      'Shopping cart badge updating immediately when an item is added',
      'Active/selected state on navigation items showing current page',
      'Loading skeleton screens that show the structure of incoming content',
      'Breadcrumbs showing the user\'s location in the site hierarchy',
      'Form input validation feedback as the user types',
      'Status indicators (online/offline, saved/unsaved) for real-time applications',
    ],
    violationExamples: [
      'Clicking a button with no visual response — user wonders if the click registered',
      'Long-running operations with no progress indicator',
      'Form submission with no success/error feedback',
      'Navigation state that doesn\'t reflect the current page',
      'Drag-and-drop without visual indicator of valid drop zones',
      'Background sync that completes silently without notification',
    ],
    evaluationQuestions: [
      'Does the system immediately acknowledge user actions (clicks, submissions, etc.)?',
      'Are loading states clearly communicated with appropriate indicators?',
      'Can the user always tell where they are in the navigation/workflow?',
      'Does the system provide progress feedback for multi-step or long operations?',
      'Are state changes (saved, syncing, offline) clearly indicated?',
      'Is feedback timely — within 100ms for immediate actions, 1s for system responses?',
    ],
  },
  {
    id: 2,
    name: 'Match Between System and Real World',
    description: 'The design should speak the users\' language. Use words, phrases, and concepts familiar to the user, rather than internal jargon. Follow real-world conventions, making information appear in a natural and logical order.',
    goodExamples: [
      'E-commerce "shopping cart" metaphor familiar to users',
      'Calendar app using month/week/day views matching physical calendars',
      'Using "Trash" or "Recycle Bin" for deleted items with recovery option',
      'Medical app using patient-friendly terms with technical terms in tooltips',
      'Date formats matching the user\'s locale (MM/DD for US, DD/MM for EU)',
      'Icons that match real-world objects (envelope for email, phone for calls)',
    ],
    violationExamples: [
      'Technical error messages like "Error 500: Internal Server Error"',
      'Database field names shown in the UI ("usr_fname" instead of "First Name")',
      'Non-standard date formats without locale awareness',
      'Using internal project codenames in user-facing text',
      'Sort order that doesn\'t match user expectation (alphabetical for a process that is sequential)',
      'Technical jargon in a consumer-facing application',
    ],
    evaluationQuestions: [
      'Is the language familiar to the target users, not the development team?',
      'Do metaphors and icons match real-world concepts users already understand?',
      'Is information ordered in a way that matches users\' expectations?',
      'Are dates, numbers, and currencies formatted for the user\'s locale?',
      'Are error messages written in plain language with actionable guidance?',
      'Would a new user understand the terminology without training?',
    ],
  },
  {
    id: 3,
    name: 'User Control and Freedom',
    description: 'Users often perform actions by mistake. They need a clearly marked "emergency exit" to leave the unwanted action without having to go through an extended process. Support undo and redo.',
    goodExamples: [
      'Undo option after deleting an email ("Message moved to trash — Undo")',
      'Cancel button in every dialog and form',
      'Browser back button works correctly in single-page applications',
      'Multi-step forms with "Back" button and step navigation',
      'Draft auto-save so users don\'t lose work',
      'Clear/reset search filters with one click',
      'Escape key closes modals and popovers',
    ],
    violationExamples: [
      'Permanent deletion with no undo or recovery option',
      'Wizard with no "Back" button — must restart from beginning',
      'Modal that can only be closed by completing the action (no cancel/close)',
      'Browser back button breaks the application state',
      'Form that loses all data when navigating away',
      'No way to deselect or change an option once selected',
    ],
    evaluationQuestions: [
      'Can users easily undo their last action?',
      'Is there always a clear way to go back, cancel, or exit?',
      'Does the browser back button work as users expect?',
      'Are destructive actions reversible, or at minimum, confirmed?',
      'Can users exit multi-step processes without losing all progress?',
      'Is there a global Escape key or gesture to dismiss overlays?',
    ],
  },
  {
    id: 4,
    name: 'Consistency and Standards',
    description: 'Users should not have to wonder whether different words, situations, or actions mean the same thing. Follow platform and industry conventions. Internal consistency matters too — use the same patterns throughout your product.',
    goodExamples: [
      'Consistent button styles: primary (filled) for main actions, secondary (outlined) for alternatives',
      'Form labels always positioned in the same location (above or beside inputs)',
      'Following platform conventions: left-aligned menus on web, bottom tabs on mobile',
      'Consistent use of color: red for destructive, green for success, blue for links',
      'Same confirmation pattern for all destructive actions',
      'Consistent spacing and sizing system throughout the application',
    ],
    violationExamples: [
      'Save button on the left in some forms, on the right in others',
      'Inconsistent terminology: "Delete" in one place, "Remove" in another, "Discard" in a third',
      'Different navigation patterns on different pages of the same app',
      'Links styled differently in different sections',
      'Inconsistent icon usage: search icon means "search" in nav but "filter" on a page',
      'Non-standard interactive patterns (e.g., green for cancel, red for save)',
    ],
    evaluationQuestions: [
      'Are the same actions labeled and styled consistently throughout the product?',
      'Does the design follow platform conventions that users already know?',
      'Is terminology consistent — same concept, same word everywhere?',
      'Are layout patterns (forms, cards, tables) reused consistently?',
      'Do colors carry consistent meaning (error = red, success = green)?',
      'Would a user who learned one part of the app immediately understand another part?',
    ],
  },
  {
    id: 5,
    name: 'Error Prevention',
    description: 'Good error messages are important, but the best designs carefully prevent problems from occurring in the first place. Either eliminate error-prone conditions, or check for them and present users with a confirmation option before they commit to the action.',
    goodExamples: [
      'Disabling the "Submit" button until all required fields are valid',
      'Inline validation that catches errors before form submission',
      'Confirmation dialog before deleting or overwriting data',
      'Type-ahead suggestions preventing spelling errors',
      'Date pickers instead of free-text date input',
      'Constraints that prevent invalid input (maxlength, input type, min/max)',
      'Autosave preventing data loss from accidental navigation',
    ],
    violationExamples: [
      'Free-text date field with no validation until submit',
      'Allowing users to submit obviously invalid data',
      'No confirmation before irreversible destructive actions',
      'Form that allows submission of duplicate entries',
      'No constraints on numeric fields (accepting letters)',
      'Delete button next to Edit button with no confirmation',
    ],
    evaluationQuestions: [
      'Are error-prone interactions designed out where possible (dropdowns vs free text)?',
      'Does the system validate input before the user tries to submit?',
      'Are destructive actions protected by confirmation dialogs?',
      'Does the system prevent duplicate submissions?',
      'Are constraints applied at the input level (maxlength, type, pattern)?',
      'Is autosave used to protect against accidental data loss?',
    ],
  },
  {
    id: 6,
    name: 'Recognition Rather Than Recall',
    description: 'Minimize the user\'s memory load by making elements, actions, and options visible. The user should not have to remember information from one part of the interface to another. Information required to use the design should be visible or easily retrievable.',
    goodExamples: [
      'Recently viewed items shown on return visit',
      'Autocomplete suggestions based on past input',
      'Visible labels on navigation items (not icon-only)',
      'Contextual tooltips explaining uncommon actions',
      'Form fields pre-filled with user\'s known data',
      'Breadcrumbs showing navigation path',
      'Dropdown showing all available options instead of requiring user to know codes',
    ],
    violationExamples: [
      'Requiring users to memorize codes or IDs to look up records',
      'Icon-only toolbars with no labels or tooltips',
      'Requiring users to remember values from a previous page/step',
      'Hidden navigation that requires users to know swipe gestures exist',
      'Error messages referencing field names not visible on screen',
      'CLI-like interfaces where users must remember commands',
    ],
    evaluationQuestions: [
      'Can users see all available options rather than having to recall them?',
      'Do icons have visible labels or at minimum accessible tooltips?',
      'Is information from previous steps visible when needed later?',
      'Are frequently used actions easily visible, not buried in menus?',
      'Does the system reduce memory load with recent items, suggestions, or defaults?',
      'Can users complete tasks without memorizing system-specific information?',
    ],
  },
  {
    id: 7,
    name: 'Flexibility and Efficiency of Use',
    description: 'Shortcuts — hidden from novice users — can speed up the interaction for the expert user so that the design can cater to both inexperienced and experienced users. Allow users to tailor frequent actions.',
    goodExamples: [
      'Keyboard shortcuts for power users (Ctrl+K command palette)',
      'Customizable dashboard with drag-and-drop widgets',
      'Saved search filters and presets',
      'Double-click to edit inline (with explicit Edit button for discoverability)',
      'Bulk actions for multi-select operations',
      'Recent/favorite items for quick access',
      'Right-click context menus as shortcuts to menu actions',
    ],
    violationExamples: [
      'No keyboard shortcuts in a productivity application',
      'Every action requires the same number of clicks, regardless of frequency',
      'No way to customize or personalize the interface',
      'Repetitive tasks without a batch/bulk mode',
      'Settings that must be changed one at a time with no "Apply to all" option',
      'No quick-access mechanism for frequently used features',
    ],
    evaluationQuestions: [
      'Are there accelerators (shortcuts, gestures) for frequent actions?',
      'Can experienced users skip steps that novice users need?',
      'Is the interface customizable for different user preferences?',
      'Are repetitive tasks optimized with bulk actions or templates?',
      'Are there multiple ways to accomplish the same task (menu, shortcut, context menu)?',
      'Does the system learn from user behavior to surface relevant options?',
    ],
  },
  {
    id: 8,
    name: 'Aesthetic and Minimalist Design',
    description: 'Interfaces should not contain information that is irrelevant or rarely needed. Every extra unit of information in an interface competes with the relevant units of information and diminishes their relative visibility.',
    goodExamples: [
      'Clean, focused forms showing only essential fields (progressive disclosure for advanced)',
      'Dashboard showing key metrics with drill-down for details',
      'Error messages that are concise and actionable',
      'White space used to create visual hierarchy and reduce cognitive load',
      'Progressive disclosure: show basics first, reveal complexity on demand',
      'Minimal onboarding: just enough to get started, with "Learn more" links',
    ],
    violationExamples: [
      'Cluttered dashboards showing every possible metric at once',
      'Long forms with 30+ fields on a single page',
      'Dense paragraphs of instructional text nobody reads',
      'Multiple competing calls-to-action on a single screen',
      'Excessive use of color, animation, and decoration that distracts',
      'Unnecessary confirmation dialogs for non-destructive actions',
    ],
    evaluationQuestions: [
      'Does every element on the screen serve a clear purpose?',
      'Is visual hierarchy clear — can users immediately identify the primary action?',
      'Is information density appropriate — not too sparse, not too cluttered?',
      'Is complexity hidden behind progressive disclosure when appropriate?',
      'Does white space effectively separate content groups?',
      'Are decorative elements adding value or just adding noise?',
    ],
  },
  {
    id: 9,
    name: 'Help Users Recognize, Diagnose, and Recover from Errors',
    description: 'Error messages should be expressed in plain language (no error codes), precisely indicate the problem, and constructively suggest a solution.',
    goodExamples: [
      '"Password must be at least 8 characters with one uppercase letter and one number" (specific format guidance)',
      '"Email address not found. Check the spelling or create a new account." (suggests next step)',
      '"Could not save — you appear to be offline. Changes will be saved when you reconnect." (explains situation and recovery)',
      'Inline field errors with specific fix suggestions',
      'Error pages with search, navigation, and contact links',
      '"File too large (50MB max). Try compressing the image." (states limit and suggests fix)',
    ],
    violationExamples: [
      '"Error 422: Unprocessable Entity" (technical jargon)',
      '"Invalid input" with no indication of what is invalid or how to fix it',
      '"Something went wrong. Please try again." (vague, unhelpful)',
      'Error message disappears too quickly to read',
      'Error page with no way to navigate back to the application',
      'Error text in red only — no icon, no clear association with the problematic field',
    ],
    evaluationQuestions: [
      'Are error messages written in plain language, free of technical jargon?',
      'Do error messages specifically identify the problem?',
      'Do error messages suggest how to fix the problem?',
      'Are errors visible, persistent enough to read, and clearly associated with their source?',
      'Can users easily recover from errors without losing their work?',
      'Do error pages provide navigation options to get back on track?',
    ],
  },
  {
    id: 10,
    name: 'Help and Documentation',
    description: 'It\'s best if the system doesn\'t need additional explanation. However, it may be necessary to provide documentation to help users understand how to complete their tasks. Help content should be easy to search, focused on the user\'s task, and list concrete steps.',
    goodExamples: [
      'Contextual help tooltips next to complex form fields',
      'Searchable help center with task-oriented articles',
      'Interactive onboarding tour for new users',
      'Inline documentation with examples in developer tools',
      'FAQ page addressing common issues',
      'Chatbot or help widget for immediate assistance',
      'Keyboard shortcut reference (Cmd+/ or ? key)',
    ],
    violationExamples: [
      'No help documentation at all',
      'Help documentation that is outdated or incomplete',
      'Lengthy manual with no search or structure',
      'Help content written for developers, not end users',
      'No contextual help — users must leave the app to find answers',
      'Complex features with no onboarding or getting-started guide',
    ],
    evaluationQuestions: [
      'Is help available contextually, near where users need it?',
      'Is help content searchable and well-organized?',
      'Is help content task-oriented with concrete steps?',
      'Is there onboarding for new users to learn key features?',
      'Are keyboard shortcuts and advanced features documented?',
      'Can users get help without leaving their current context?',
    ],
  },
] as const;
